export const SKILL_ID_TO_LABEL = {
	azure: 'Microsoft Azure',
	ansible: 'Ansible',
	aws: 'Amazon Web Services',
	c: 'C',
	chrome: 'Chrome',
	cloudformation: 'CloudFormation',
	docker: 'Docker',
	firebase: 'Firebase',
	flask: 'Flask',
	gcp: 'Google Cloud Platform',
	graphql: 'GraphQL',
	java: 'Java',
	javascript: 'JavaScript',
	mysql: 'MySQL',
	nextjs: 'Next.js',
	nginx: 'NGINX',
	nodejs: 'Node.js',
	python: 'Python',
	rabbitmq: 'RabbitMQ',
	reactjs: 'React',
	reactnative: 'React Native',
	redux: 'Redux',
	rest: 'REST',
	rust: 'Rust',
	scikit: 'scikit-learn',
	spring: 'Spring',
	svelte: 'Svelte',
	sveltekit: 'SvelteKit',
	swift: 'Swift',
	tailwindcss: 'TailwindCSS',
	tensorflow: 'TensorFlow',
	typescript: 'TypeScript',
	wasm: 'WebAssembly',
	vim: 'Vim',
};

export type Skill = keyof typeof SKILL_ID_TO_LABEL;
